name: "dagster-cloud ci <command>"
description: "Run a dagster-cloud cli command"
inputs:
  command:
    required: true
    description: "The dagster-cloud cli command to run"
  dagster_cloud_url:
    required: false
    description: 'Full Dagster Cloud URL override'

runs:
  using: "composite"
  steps:
    - id: dagster-cloud-cli
      run: |
        ${{ inputs.dagster_cloud_url && format('export DAGSTER_CLOUD_URL="{0}"', inputs.dagster_cloud_url) || '' }}
        $GITHUB_ACTION_PATH/../../../generated/gha/dagster-cloud.pex -m dagster_cloud_cli.entrypoint ${{ inputs.command }}
      shell: bash
